### ISSUE TITLE
sampler master fails

### ISSUE THREAD

**Issue by TamimiGitHub** [SolaceSamples/solace-samples-python#16]
Getting the following error when running the sampler master 

solace.messaging.core: [_solace_session.py:801]  [[SERVICE: 0x106068f60] - [APP ID: app_5338d678-db83-4db3-b832-bc231049045c]] {'caller_description': 'From service event callback', 'return_code': 'Ok', 'sub_code': 'SOLCLIENT_SUBCODE_COMMUNICATION_ERROR', 'error_info_sub_code': 14, 'error_info_contents': 'TCP connection failure for fd 9, error = Connection refused (61)'}

**Comment by sdewilde** [comment]
I had the same problem initially, is the server certificate set up on the broker?

**Comment by TamimiGitHub** [comment]
Yea I updated the solbroker_properties and now have this error

```
2021-05-20 17:21:35,827 [WARNING] solace.messaging.core: [_solace_session.py:801]  [[SERVICE: 0x11187fb00] - [APP ID: app_46e048b4-fe67-469f-b923-5457e72f30c2]] {'caller_description': 'From service event callback', 'return_code': 'Ok', 'sub_code': 'SOLCLIENT_SUBCODE_COMMUNICATION_ERROR', 'error_info_sub_code': 14, 'error_info_contents': 'TCP connection failure for fd 13, error = Connection refused (61)'}
2021-05-20 17:21:35,827 [WARNING] solace.messaging.core: [_solace_session.py:709]  [[SERVICE: 0x11187fb00] - [APP ID: app_46e048b4-fe67-469f-b923-5457e72f30c2]] {'caller_description': 'do_connect', 'return_code': 'Not ready', 'sub_code': 'SOLCLIENT_SUBCODE_COMMUNICATION_ERROR', 'error_info_sub_code': 14, 'error_info_contents': 'TCP connection failure for fd 13, error = Connection refused (61)'}
Traceback (most recent call last):
  File "howtos/sampler_master.py", line 61, in <module>
    SamplerMaster.run_samplers()
  File "howtos/sampler_master.py", line 42, in run_samplers
    HowToConnectWithTls.run()
  File "/Users/taltamimi/samples/python/howtos/extras/how_to_configure_transport_layer_security.py", line 115, in run
    trust_store_path=trust_store_path_name)
  File "/Users/taltamimi/samples/python/howtos/extras/how_to_configure_transport_layer_security.py", line 46, in tls_with_certificate_validation_and_trusted_store_settings
    messaging_service.connect()
  File "/Users/taltamimi/samples/python/venv/lib/python3.7/site-packages/solace/messaging/messaging_service.py", line 553, in connect
    connect_status = self._api._session_connect()
  File "/Users/taltamimi/samples/python/venv/lib/python3.7/site-packages/solace/messaging/core/_solace_session.py", line 487, in _session_connect
    return self.__do_connect()
  File "/Users/taltamimi/samples/python/venv/lib/python3.7/site-packages/solace/messaging/core/_solace_session.py", line 691, in __do_connect
    self.__handle_exception_message(return_code=return_code, caller_desc='do_connect')
  File "/Users/taltamimi/samples/python/venv/lib/python3.7/site-packages/solace/messaging/core/_solace_session.py", line 710, in __handle_exception_message
    raise PubSubPlusCoreClientError(message=core_exception_msg, sub_code=info_sub_code)
solace.messaging.errors.pubsubplus_client_error.PubSubPlusCoreClientError: {'caller_description': 'do_connect', 'return_code': 'Not ready', 'sub_code': 'SOLCLIENT_SUBCODE_COMMUNICATION_ERROR', 'error_info_sub_code': 14, 'error_info_contents': 'TCP connection failure for fd 13, error = Connection refused (61)'}
```

I will investigate what could be this issue. Looks like it has something to do with `tls_with_certificate_validation_and_trusted_store_settings`
